#!/usr/bin/env bash
#Install nginx web server

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
sudo sed -i '24i\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
