#!/usr/bin/env bash
#Update the package list and install HAProxy

sudo apt-get update -y
sudo apt-get install -y haproxy
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend gracekamondo.tech
    timeout client  30000
    bind 0:80
    default_backend gracekamondo.tech

backend gracekamondo.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 261478-web-01 34.229.69.25:80 check
    server 261478-web-02 100.26.227.84:80 check
EOT

sudo service haproxy restart
