#!/usr/bin/env bash
#Bash script that pings an IP address passed as an argument

if [ $# -ne 1 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

IP_ADDRESS=$1

echo "Pinging $IP_ADDRESS 5 times..."
for ((i=1; i<=5; i++))
do
    ping -c 1 $IP_ADDRESS >/dev/null
    if [ $? -eq 0 ]; then
        echo "Ping $i: $IP_ADDRESS is online."
    else
        echo "Ping $i: $IP_ADDRESS is offline."
    fi
done
