#!/usr/bin/env bash
#Bash script displaying PID and process name bash

if [ "$EUID" -ne 0 ]; then
  echo "This script requires superuser privileges to access the /proc directory."
  exit 1
fi

for pid_dir in /proc/[0-9]*/; do
  pid=$(basename "$pid_dir")

process_name=$(tr -d '\0' < "$pid_dir/cmdline")

if [[ "$process_name" == *"bash"* ]]; then
    echo "$pid $process_name"
  fi
done


