#!/usr/bin/env bash
#Bash script writes file and in between every message pauses for 2 seconds

start_process() {
    if [ -f "/var/run/my_process.pid" ]; then
        echo "manage_my_process is already running. PID: $(cat /var/run/my_process.pid)"
    else
        echo "Starting manage_my_process..."
        ./manage_my_process & echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
    fi
}

stop_process() {
    if [ -f "/var/run/my_process.pid" ]; then
        echo "Stopping manage_my_process..."
        kill "$(cat /var/run/my_process.pid)"
        rm -f /var/run/my_process.pid
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running."
    fi
}

case "$1" in
    "start")
        start_process
        ;;
    "stop")
        stop_process
        ;;
    "restart")
        stop_process
        start_process
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        ;;
esac
