#!/usr/bin/env bash
#Bash script displaying numbers from 1 to 20 using while loop

count=1
while ((count < 21))
do
	echo $count
    case $count in
        4)
	    echo "bad luck from China"
	    ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    ((count++))
done
