#!/usr/bin/env bash
#Bash script using while loop to display time for 12hrs and 59 minutes

hour=0
minute=1
while [ $hour -ne 13 ]
do
    echo "Hour: $hour"
    ((hour++))
    while [ $minute -ne 60 ]
    do
	echo $minute
	((minute++))
    done
    ((minute = 1))
done
