#!/usr/bin/env bash
#Bash script using while loop to display current directory content, list format and part of name

for file in *; do

    if [[ ! "$file" =~ ^\..* ]]; then

        name_after_dash=$(echo "$file" | cut -d'-' -f2-)
        
        echo "$name_after_dash"
    fi
done
