#!/usr/bin/env bash
#Bash script to configure Ubuntu server

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.temp
echo "8.8.8.8		facebook.com" >> ~/hosts.temp
cp -f ~/hosts.new /etc/hosts
