#!/usr/bin/env bash
#Bash script that listens on port 98 on localhost

echo "Starting my script."

nc -l -p 98 | while read -r line; do
    echo "Received: $line"
    echo "Sending response..."
    echo "Response from server: Hello, client! You said: $line" | nc -q 0 localhost 98
done
