#!/usr/bin/env bash
#SSH configuration file

Host 261478-web-01
    HostName 34.229.69.25
    User ubuntu    
    IdentityFile ~/.ssh/school
    PreferredAuthentications publickey
    PasswordAuthentication no
